/// Flutter icons CustomIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const String? _kFontPkg = null;

  static const IconData up_2iconfluttter = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bagiconfluttter2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_2iconfluttter = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData showiconfluttter = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_2iconfluttter = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locationiconfluttter = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logouticonfluttter = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_2iconfluttter = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downloadiconfluttter = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_2iconfluttter = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData closeiconfluttter__2_ = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_2iconfluttter = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hideiconfluttter = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discount_shape_1iconfluttter = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walleticonfluttter = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_delete_1iconfluttter = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_remove_1iconfluttter = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_2iconfluttter = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift_1iconfluttter = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData categoryiconfluttter__2_ = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information_circleiconfluttter = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_36iconfluttter = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_2iconfluttter = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_1iconfluttter = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_circleiconfluttter = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_align_left_5iconfluttter = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_1iconfluttter = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faq_circleiconfluttter = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_1iconfluttter = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buy_2iconfluttter = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_add_1iconfluttter = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_1iconfluttter = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_2iconfluttter = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_4iconfluttter = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_circleiconfluttter = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_3iconfluttter = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_squareiconfluttter = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_3iconfluttter = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paletteiconfluttter__2_ = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password_1iconfluttter = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minusiconfluttter__2_ = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addiconfluttter__2_ = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_4iconfluttter = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick_circleiconfluttter = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick_squareiconfluttter = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun_2iconfluttter = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mooniconfluttter__2_ = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tickiconfluttter__2_ = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hearticonfluttter = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minusiconfluttter = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faqcircleiconfluttter = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lefticonfluttter = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mooniconfluttter = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData morecircleiconfluttter = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messageiconfluttter = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData informationcircleiconfluttter = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationiconfluttter = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downiconfluttter = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData righticonfluttter = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData categoryiconfluttter = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upiconfluttter = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tickcircleiconfluttter = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardiconfluttter = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home2iconfluttter = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData callicon = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bagiconfluttter = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addiconfluttter = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password_2icon = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_1icon = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stariconfluttter = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tickiconfluttter = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paletteiconfluttter = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticksquareiconfluttter = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData closeiconfluttter = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shieldiconfluttter = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sms_2icon = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData websiteiconfluttter = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_kebabiconfluttter = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_1iconfluttter = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
